packages:
  - '.'
  - 'example'
allowBuilds:
  esbuild: true
minimumReleaseAgeExclude:
  - '@starbemtech/react-starsystem@0.2.0 || 0.3.0'
overrides:
  postcss: '^8.5.18'
  'brace-expansion@>=2.0.0 <2.1.2': '^2.1.2'
